version: '3.8'

services:
  reversi-shallowbrain:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
    restart: unless-stopped